### ISSUE TITLE
Deprecate npme public docs and npme docs repo

### ISSUE THREAD

**Issue by neverett** [npm/npmo-docs#82]
#### TODO

* [x] Add a "these docs are deprecated" notice to public-facing Enterprise docs index page
* [x] Link to (as-yet nonexistent) new Enterprise admin docs on public-facing docs index page
* [ ] Make this repo private
* [ ] Archive this repo

#### Blocked on

* Publicly shipping new Enterprise docs

**Comment by neverett** [comment]
New Enterprise docs are at https://docs.npmjs.com/enterprise and there is a banner on legacy Enterprise docs directing folks to that URL. Holding off on putting a deprecation notice on the README and/or archiving this repo for now.
